language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_script:
    - "chmod +x gradlew"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
    - "./gradlew clean build"

notifications:
  email:
    recipients:
      - dylee0568@gmail.com