language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# before_script는 동작 X
before_install:
    - "chmod +x gradlew"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
    - "./gradlew clean build"

before_deploy:
  - zip -r hosp *
  - mkdir -p deploy
  - mv hosp.zip deploy/hosp.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hosp-bucket-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - dylee0568@gmail.com